In [1]:
import QUANTAXIS as QA

QUANTAXIS>> start QUANTAXIS
QUANTAXIS>> Selecting the Best Server IP of TDX

Bad REPSONSE 180.153.18.17
Bad REPSONSE sztdx.gtjas.com

QUANTAXIS>> === The BEST SERVER ===
 stock_ip 115.238.56.198 future_ip 61.152.107.141
QUANTAXIS>> Welcome to QUANTAXIS, the Version is 1.0.15
QUANTAXIS>>
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
  ``########`````##````````##``````````##`````````####````````##```##########````````#``````##``````###```##`````######``
  `##``````## ```##````````##`````````####````````##`##```````##```````##```````````###``````##````##`````##```##`````##`
  ##````````##```##````````##````````##`##````````##``##``````##```````##``````````####```````#```##``````##```##``````##
  ##````````##```##````````##```````##```##```````##```##`````##```````##`````````##`##```````##`##```````##````##```````
  ##````````##```##````````##``````##`````##``````##````##````##```````##````````##``###```````###````````##`````##``````
  ##````````##```##````````##``````##``````##`````##`````##```##```````##```````##````##```````###````````##``````###````
  ##````````##```##````````##`````##````````##````##``````##``##```````##``````##``````##`````##`##```````##````````##```
  ##````````##```##````````##````#############````##```````##`##```````##`````###########`````##``##``````##`````````##``
  ###```````##```##````````##```##```````````##```##```````##`##```````##````##`````````##```##```##``````##```##`````##`
  `##``````###````##``````###``##`````````````##``##````````####```````##```##``````````##``###````##`````##````##`````##
  ``#########``````########```##``````````````###`##``````````##```````##``##````````````##`##``````##````##`````###``###
  ````````#####`````````````````````````````````````````````````````````````````````````````````````````````````````##``
  ```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
  ``````````````````````````Copyright``yutiansut``2017``````QUANTITATIVE FINANCIAL FRAMEWORK`````````````````````````````
  ```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
 ````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

In [2]:
code=QA.QA_fetch_stock_block_adv().code

In [3]:
data=QA.QA_fetch_stock_day_adv(code,'2018-02-01','2018-03-16')

In [4]:
data.data['zf']=data.bar_amplitude  #日振幅

In [5]:
data.data['zf_diff']=data.data.zf.diff()

In [6]:
#data.add_func(model1)

# 先要找到一个key_point

In [7]:
data.data['zhf']=abs(data.bar_pct_change)
data.data['rzhf']=data.bar_pct_change
#data.data['rzhf_diff']=data.bar_pct_change.diff()
data.data['amount']=data.amount

In [8]:
data.query('zf>0.08').query('rzhf<-0.06').query('amount>500000000').xs('2018-03-12',level=0)

,code,open,high,low,close,volume,date,high_limit,low_limit,zf,zf_diff,zhf,rzhf,amount
code,,,,,,,,,,,,,,
002929,002929,60.50,61.27,55.45,55.68,331790.0,2018-03-12,51.70,42.30,0.104959,0.043832,0.079669,-0.079669,1.931847e+09
300739,300739,48.52,50.49,43.98,44.61,150346.0,2018-03-12,79.81,65.30,0.148022,0.018981,0.080585,-0.080585,7.051227e+08
601155,601155,38.70,38.88,34.79,34.95,455201.0,2018-03-12,8.44,6.90,0.117563,0.109689,0.096899,-0.096899,1.676505e+09
603516,603516,66.45,66.45,59.00,59.53,159837.0,2018-03-12,52.87,43.25,0.126271,0.097736,0.104138,-0.104138,1.004695e+09
603895,603895,64.10,65.73,57.50,58.51,122695.0,2018-03-12,37.61,30.77,0.143130,0.108536,0.087207,-0.087207,7.540835e+08

In [9]:
data.query('zf>0.08').query('zf_diff>0.14').query('rzhf>0.06').query('amount>500000000')

,,code,open,high,low,close,volume,date,high_limit,low_limit,zf,zf_diff,zhf,rzhf,amount
date,code,,,,,,,,,,,,,,
2018-02-08,300104,300104,4.34,5.28,4.34,5.08,8783692.0,2018-02-08,8.22,6.72,0.216590,0.168314,0.170507,0.170507,4.181037e+09
2018-02-09,603871,603871,72.87,80.29,68.10,80.29,99932.0,2018-02-09,20.60,16.86,0.179001,0.140708,0.101825,0.101825,7.533624e+08
2018-02-12,002086,002086,9.27,11.00,9.27,9.91,647027.0,2018-02-12,6.46,5.28,0.186624,0.141009,0.069040,0.069040,6.381304e+08
2018-02-22,002760,002760,21.69,26.50,21.69,23.00,234771.0,2018-02-22,14.00,11.46,0.221761,0.195148,0.060396,0.060396,5.451383e+08
2018-02-23,300064,300064,7.88,9.47,7.88,8.56,1027345.0,2018-02-23,4.94,4.04,0.201777,0.186117,0.086294,0.086294,8.678497e+08
2018-02-26,002650,002650,4.64,5.50,4.64,5.01,2315028.0,2018-02-26,11.14,9.12,0.185345,0.155042,0.079741,0.079741,1.145360e+09
2018-02-28,300216,300216,9.09,11.00,9.09,10.70,655385.0,2018-02-28,8.45,6.91,0.210121,0.176876,0.177118,0.177118,6.534188e+08
2018-03-06,002694,002694,10.43,12.75,10.43,12.75,1324591.0,2018-03-06,6.07,4.97,0.222435,0.163176,0.222435,0.222435,1.535201e+09
2018-03-07,002927,002927,41.48,45.63,37.33,45.63,163215.0,2018-03-07,16.21,13.27,0.222341,0.180164,0.100048,0.100048,6.939494e+08
2018-03-08,300216,300216,11.49,12.91,11.08,12.91,780288.0,2018-03-08,8.57,7.01,0.165162,0.144329,0.123586,0.123586,9.439534e+08
2018-03-15,002208,002208,13.03,14.97,12.81,14.97,504473.0,2018-03-15,8.84,7.24,0.168618,0.147045,0.148887,0.148887,7.034876e+08

# try to make a model

In [31]:
da1=data.data.xs('000002',level=1)

In [37]:
list(da1.query('rzhf<-0.06').date.apply(lambda x: str(x)[0:10]))

['2018-02-07']

In [27]:
str(da1.query('rzhf<-0.06').date[0])[0:10]

'2018-02-07'

In [30]:
da1.loc[QA.QA_util_get_next_day(str(da1.query('rzhf<-0.06').date[0])[0:10])].rzhf>0.5

False

In [17]:
da1.loc['2018-02-07']

code                       000001
open                        14.22
high                         14.3
low                         12.76
close                       12.92
volume                3.34572e+06
date          2018-02-07 00:00:00
high_limit                   7.29
low_limit                    5.97
zf                        0.12069
zf_diff                 0.0337994
zhf                     0.0914205
rzhf                   -0.0914205
amount                4.53345e+09
Name: 2018-02-07 00:00:00, dtype: object